exp_name: 0519.141850_lv2_c2f_id7im5hf6z
seed: 23
network:
  num_classes: 7
  num_levels: 2
  size: 256
  num_initial_filter: 8
  num_blocks_per_level: 3
  upskip: UpSampling3D
  conv_block: Plain
  dropout_rate: 0.05
  activation_enc: relu
  activation_dec: relu
  stride: 2
  bn: GN
  kernel_initializer: he_normal
  kernel_regularizer: 0.0001
  downsampling_factor: 4
  skip_intermediate_result: false
  pre_ds: 0
  flat_net: false
  conv_repetition: false
  filter_multiplicative_factors: []
  boost_first_layer: false
  vanilla_unet: false
  cerebrum_net: false
data:
  Path_in_data: /LOD_Brain/data/
  Path_in_csv: /LOD_Brain/data/analysis/csv/
  Filename_csv: dataset_short_training_a+a.csv
  Inh_vol_path: /LOD_Brain/data/analysis/inhomogeneity_volume/inhomogeneity.npy
  normalisation: z_score_volume
training:
  lr: 0.0005
  optimizer: Adam
  loss: per_channel_dice_loss
  ft_loss: categorical_crossentropy
  batch_size: 1
  epochs: 50
  epochs_ft: 20
  train_size: null
  validation_steps: 10
  validation_freq: 1
  weights_path: ''
  coarse_to_fine: true
  fine_tuning: false
  exp_path: !!python/object/apply:pathlib.PosixPath
  - /
  - cerebrum
  - output
  - multi_data
  - wandb
  - run-20220519_141848-7im5hf6z
  - files
  refinement: false
  ref_loss: categorical_crossentropy
  ref_lr: 1.0e-05
  ref_epochs: 10
  test_best_model: true
augment:
  augmentation: true
  prob_overall: 0.9
  prob_flip: 0.5
  prob_inho: 1.0
  prob_geom: 1.0
  prob_grid: 1.0
  prob_resi: 0.0
  prob_rota: 0.0
  prob_tran: 0.0
  prob_colo: 1.0
  prob_blur: 1.0
  prob_down: 1.0
  prob_salt: 1.0
  prob_gaus: 1.0
  prob_ghos: 1.0
  prob_gamm: 1.0
  prob_neck: 0.0
  prob_cont: 1.0
  prob_slic: 1.0
  prob_bias: 0.0
  z_score_volume: false
  augmentation_AF: false
